name = "wiki-worker-dev"
type = "javascript"
zone_id = "2b45e3853e1b35484d323689da5400d7"
account_id = "9d457b7afe76f79d16ba2f4cb8530f05"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.staging]
name = "wiki-worker-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.indiainvestments.wiki/*"

[env.production]
name = "wiki-worker-prod"
vars = { ENVIRONMENT = "production" }
route = "indiainvestments.wiki/*"
