name: Staging

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Stage
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'staging'
          secrets: |
            DISCORD_SERVER
            SUBREDDIT_LINK
            YOUTUBE_CHANNEL
        env:
          DISCORD_SERVER: ${{ secrets.DISCORD_SERVER }}
          SUBREDDIT_LINK: ${{ secrets.SUBREDDIT_LINK }}
          YOUTUBE_CHANNEL: ${{ secrets.YOUTUBE_CHANNEL }}
